// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#include "OI.h"

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES
#include "frc/smartdashboard/SmartDashboard.h"
#include "Commands/AutonomousCommand.h"
#include "Commands/JoyDrive.h"
#include "Commands/Climb.h"
#include "Commands/Deploy.h"
#include "Commands/RetractHook.h"
#include "Commands/RetractClimb.h"
#include "Commands/Dump.h"
#include "Commands/UnDump.h"
// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES

OI::OI() {
    // Process operator interface input here.
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    joy.reset(new frc::Joystick(0));
    

    // SmartDashboard Buttons
    frc::SmartDashboard::PutData("Autonomous Command", new AutonomousCommand());
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    climbing.reset(new frc::JoystickButton(joy.get(), 1));
    climbing->WhileHeld(new Climb());

    deploying.reset(new frc::JoystickButton(joy.get(), 6));
    deploying->WhileHeld(new Deploy());

    /*retracting.reset(new frc::JoystickButton(joy.get(), 3));
    retracting->WhileHeld(new RetractHook());

    retractingclimb.reset(new frc::JoystickButton(joy.get(), 4));
    retractingclimb->WhileHeld(new RetractClimb());*/

    wishDump.reset(new frc::JoystickButton(joy.get(), 5));
    wishDump->WhileHeld(new Dump());

    wishUndump.reset(new frc::JoystickButton(joy.get(), 3));
    wishUndump->WhileHeld(new UnDump());
}

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=FUNCTIONS

std::shared_ptr<frc::Joystick> OI::getjoy() {
   return joy;
}

// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=FUNCTIONS
